### ISSUE TITLE
Folder missing + ( if you can greb imei remplace name)

### ISSUE THREAD

**Issue by rammos92** [Bhartiya-Hacker/Liz-RAT#1]
Folder Missing 
Clients Db 
Client download 
i make it manually
i love the new one  
Rear and front not working tested on sdk 33
modifed 🔑 !!!!!!!! 
screen shoot also not working 
if you can remplace name of victim with imei 🙏

**Comment by Bhartiya-Hacker** [comment]
Tool will create both folders when you download any thing from the client phone

**Comment by rammos92** [comment]
you can add to change name of victim by imei serial number

**Comment by Bhartiya-Hacker** [comment]
Solved
